spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:taskdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

h2:
  console:
    enabled: true
    path: /h2-console

logging:
  level:
    root: INFO


