spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:taskdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO

#
## dev profile overrides
#---
#spring:
#  profiles: dev
#  jpa:
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#---
#spring:
#  profiles: test
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#  logging:
#    level:
#      root: WARN
