spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:taskdb
  jpa:
    hibernate:
      ddl-auto: create-drop  # recreate schema every test run
    show-sql: false

h2:
  console:
    enabled: false   # disable console in tests

logging:
  level:
    root: WARN

url: jdbc:h2:mem:testdb
